// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
<<<<<<< HEAD
    url: process.env["DATABASE_URL"] ?? "",
=======
    url: process.env["DATABASE_URL"] || "",
>>>>>>> 1980623d1f6b341b7ae7042e22a7fe4444005819
  },
});
